### ISSUE TITLE
New stations on NANOOS 52N SOS not harvested and included on map

### ISSUE THREAD

**Issue by emiliom** [ioos/freezing-avenger#14]
Following up on emails with @lance-axiom and @shane-axiom, and previously on emails with Derrick and others at IOOS.

We added several new stations to the NANOOS 52N SOS around June 23rd. As of today (July 13), they're still not showing up on the IOOS Env. Sensor Map. 

The NANOOS 52N SOS endpoint is at http://data.nanoos.org/52nsos/sos/kvp. Here are a couple of these new stations, which are currently active. Clicking on the links below will return a GeoJSON encoding based on a parsed version of most of the core attributes in their SensorML responses:
- [`urn:ioos:station:nanoos:nerrs_sosnswq`](http://data.nanoos.org/geoserver/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=sos:nanoos_sos_stations&outputFormat=json&cql_filter=%28station_urn='urn:ioos:station:nanoos:nerrs_sosnswq'%29)
- [`urn:ioos:station:nanoos:wadoh_oakland`](http://data.nanoos.org/geoserver/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=sos:nanoos_sos_stations&outputFormat=json&cql_filter=%28station_urn='urn:ioos:station:nanoos:wadoh_oakland'%29)

There are 15-20 other active stations that are also not being handled by the IOOS Env. Sensor Map. A couple of those are new (late June), but most of them have been in the SOS service but became active again in May or June, possibly even earlier.

**Comment by lance-axiom** [comment]
@emiliom I am looking into this issue now. Do you have any current stations that are not showing up on the map? I am seeing the two that you provided.

**Comment by emiliom** [comment]
@lance-axiom, sorry for the lag; your comment arrived while I was in a meeting abroad.

I'd have to do a detailed assessment to figure out which stations to test for on the Sensor Map. Otherwise, only one recently added station comes to mind: [`urn:ioos:station:nanoos:apl_nemo`](http://data.nanoos.org/geoserver/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=sos:nanoos_sos_stations&outputFormat=json&cql_filter=(station_urn='urn:ioos:station:nanoos:apl_nemo')). Data streaming was added to that station on our end a month ago (9/20), and it's been available on our SOS service since then. I just checked it on the SOS GetCapabilities, and it looks fine. But it's not on the Sensor Map.

But to be clear, what I'm really interested in is reassurance that the processes are in place (and can be confirmed/validated) that automatically pick up new stations. Otherwise it's a frustrating exercise in occasional manual checking to see that all the stations are there, right? That's really not good. If a single station can slip through the cracks for a month (and previously, as I documented on this issue, several stations slipped through for nearly a month, some probably much more) w/o a clear reason, it's hard to have confidence in the ability of the system to pick up new stations as they are added to the SOS services.

**Comment by lance-axiom** [comment]
@emiliom I confirmed that the station `urn:ioos:station:nanoos:apl_nemo` is not being added when the daily script checks for new stations. But I have not figured out why yet it is not being added. I am looking into the problem currently. I understand that you want this fixed for all stations so you do not have to check to make sure that all your stations are added each time. I have not and will not add these stations manually and they will only be added by the code that collects all the stations. So, once the problem is fixed this should allow all the stations with this problem to be added.  

I will update you as soon as I get any new information.

**Comment by lance-axiom** [comment]
@emiliom I did find the problem with the `urn:ioos:station:nanoos:apl_nemo` station. It does not have data for the last 7 days. We only display stations that have data for the last 7 days. I will look for other stations in your SOS that are missing and if they should be added. 

```
<sos:ObservationOffering gml:id="urn_ioos_station_nanoos_apl_nemo">
<gml:name>urn:ioos:station:nanoos:apl_nemo</gml:name>
<gml:boundedBy>
<gml:Envelope srsName="http://www.opengis.net/def/crs/EPSG/0/4326">
<gml:lowerCorner>47.9739990234375 -124.95500183105469</gml:lowerCorner>
<gml:upperCorner>47.9739990234375 -124.95500183105469</gml:upperCorner>
</gml:Envelope>
</gml:boundedBy>
<sos:time>
<gml:TimePeriod xsi:type="gml:TimePeriodType">
<gml:beginPosition>2016-09-10T06:58:52.000Z</gml:beginPosition>
<gml:endPosition>2016-10-25T16:58:52.000Z</gml:endPosition>
</gml:TimePeriod>
</sos:time>
<sos:procedure xlink:href="urn:ioos:station:nanoos:apl_nemo"/>
<sos:observedProperty xlink:href="NONE"/>
<sos:observedProperty xlink:href="http://mmisw.org/ont/cf/parameter/mass_concentration_of_oxygen_in_sea_water"/>
<sos:observedProperty xlink:href="http://mmisw.org/ont/cf/parameter/sea_water_pressure"/>
<sos:observedProperty xlink:href="http://mmisw.org/ont/cf/parameter/sea_water_salinity"/>
<sos:observedProperty xlink:href="http://mmisw.org/ont/cf/parameter/sea_water_temperature"/>
<sos:featureOfInterest xlink:href="urn:ioos:station:nanoos:apl_nemo(height0.0m)"/>
<sos:responseFormat>application/json</sos:responseFormat>
<sos:responseFormat>application/zip; subtype=x-netcdf</sos:responseFormat>
<sos:responseFormat>text/xml; subtype="om/1.0.0"</sos:responseFormat>
<sos:responseFormat>text/xml; subtype="om/1.0.0/profiles/ioos_sos/1.0"</sos:responseFormat>
<sos:responseMode>inline</sos:responseMode>
<sos:responseMode>resultTemplate</sos:responseMode>
</sos:ObservationOffering>
```

**Comment by emiliom** [comment]
Thanks @lance-axiom. The perils of asynchronous work :wink: ... When I said on Oct 5 that `urn:ioos:station:nanoos:apl_nemo` was online, that was true at that moment. But, now, your asessment that the station hasn't had data in the last 7 days is also true! The mooring was recovered on Oct 25 or 26, ~ 8 days ago. Sigh.

There's one new station that will be added into the SOS service very soon. I thought it would've been added by now, but an idiosyncratic twist got in the way. I'll look into it and will try to add it today or tomorrow. I'll let you know once it's there, so you can use it as a test. Otherwise, I can't think of any other newish stations; I'd have to dig deeper.

We're completely on the same page about the end goal of station updates/loading being automatic:
> I understand that you want this fixed for all stations so you do not have to check to make sure that all your stations are added each time. I have not and will not add these stations manually and they will only be added by the code that collects all the stations. So, once the problem is fixed this should allow all the stations with this problem to be added.

**Comment by emiliom** [comment]
The new station is now available on the NANOOS SOS. Station urn: `urn:ioos:station:nanoos:nerrs_sostcmet`. FYI, I confirmed it on the GetCapabilities and DescribeSensor requests, but not on GetObservation. This is a meteorological station in Oregon.

**Comment by lance-axiom** [comment]
Ok, I will look into that station now to see why it is not added.

**Comment by lance-axiom** [comment]
@emiliom I found and fixed the problem we were see with the addition of new stations from the SOS. The process was getting an error and was not finishing collecting all the stations. 

Thank you for your help in figuring out this problem. I am currently adding more visibility to the ingest process so these problems can not seen easier.

**Comment by emiliom** [comment]
Fantastic! Thanks so much.
